sudo: required
services:
  - docker

before_install:
  - docker build -t paarasjamwal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true paarasjamwal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-471229560361"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY